# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.10.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aiokubernetes
from aiokubernetes.models.v2beta1_horizontal_pod_autoscaler_status import V2beta1HorizontalPodAutoscalerStatus  # noqa: E501
from aiokubernetes.rest import ApiException


class TestV2beta1HorizontalPodAutoscalerStatus(unittest.TestCase):
    """V2beta1HorizontalPodAutoscalerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2beta1HorizontalPodAutoscalerStatus(self):
        """Test V2beta1HorizontalPodAutoscalerStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aiokubernetes.models.v2beta1_horizontal_pod_autoscaler_status.V2beta1HorizontalPodAutoscalerStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
