# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.10.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aiokubernetes
from aiokubernetes.models.policy_v1beta1_run_as_user_strategy_options import PolicyV1beta1RunAsUserStrategyOptions  # noqa: E501
from aiokubernetes.rest import ApiException


class TestPolicyV1beta1RunAsUserStrategyOptions(unittest.TestCase):
    """PolicyV1beta1RunAsUserStrategyOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicyV1beta1RunAsUserStrategyOptions(self):
        """Test PolicyV1beta1RunAsUserStrategyOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aiokubernetes.models.policy_v1beta1_run_as_user_strategy_options.PolicyV1beta1RunAsUserStrategyOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
