# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.10.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aiokubernetes
from aiokubernetes.models.v2beta1_pods_metric_source import V2beta1PodsMetricSource  # noqa: E501
from aiokubernetes.rest import ApiException


class TestV2beta1PodsMetricSource(unittest.TestCase):
    """V2beta1PodsMetricSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2beta1PodsMetricSource(self):
        """Test V2beta1PodsMetricSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aiokubernetes.models.v2beta1_pods_metric_source.V2beta1PodsMetricSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
