services:
  - docker

matrix:
    include:
     - env: PYTHON_IMAGE=python:3.6-alpine3.7
     - env: PYTHON_IMAGE=python:3.7-alpine3.7

script:
  - docker run -ti -v`pwd`:/src $PYTHON_IMAGE /bin/ash -c "cd /src; ash scripts/run-ci-tests.sh"
